🚌 Projet MDM - Mobilité Durable en Montagne ⛰️

*Author : Nicolas Grosjean*

*Date : 09/11/2025*

**Description :**

Analyses bus data with C2C activity points :
- Compute distance between them
- Identify C2C activity points not deserved
- Make pretty visualisations to share

In [1]:
# WORKING DIR NEED TO BE SET BEFORE IMPORTING SETTINGS
import os

os.chdir("../..")
print("Working directory set to the root of the project")

Working directory set to the root of the project

In [2]:
import folium
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point, box

from src.settings import DATA_FOLDER, EPSG_WEB_MERCATOR, EPSG_WGS84

In [3]:
department_code = "74"
neighbour_department_codes = {
    "38": ["1", "5", "8", "26", "42", "69", "73"],
    "73": ["1", "5", "38", "74"],
    "74": ["1", "73"],
}

## Read data

In [4]:
from src.processors.osm import AURAOSMBusLinesProcessor, AURAOSMBusStopsProcessor

In [5]:
osm_stops_gdf = AURAOSMBusStopsProcessor.fetch(reload_pipeline=False)
osm_stops_gdf.loc[:, "source"] = "OSM"
osm_stops_gdf.head()

,gtfs_id,navitia_id,osm_id,name,description,line_gtfs_ids,line_osm_ids,network,network_gtfs_id,geometry,other,source
0,NaN,None,135296,Université - IUT-STAPS,NaN,[],[3922428],M réso,None,POINT (5.77622 45.19738),"{'access': None, 'addr:city': None, 'addr:hous...",OSM
1,NaN,None,135930,Hôpital Couple Enfant,NaN,[],"[3333927, 3922430]",M réso,None,POINT (5.74231 45.20065),"{'access': None, 'addr:city': None, 'addr:hous...",OSM
2,NaN,None,136570,Cap des H',"Arrêt de régulation, non commercial.",[],[],M réso,None,POINT (5.68159 45.21695),"{'access': None, 'addr:city': None, 'addr:hous...",OSM
3,NaN,None,136597,Place de la Libération,NaN,[],"[3031947, 3031948, 3044780, 3044781, 3923550, ...",M réso,None,POINT (5.66272 45.20707),"{'access': None, 'addr:city': None, 'addr:hous...",OSM
4,NaN,None,137073,Centr'Alp 2,NaN,[],"[3090127, 8671286, 8671287]",M réso,None,POINT (5.6043 45.3198),"{'access': None, 'addr:city': None, 'addr:hous...",OSM

In [6]:
osm_lines_gdf = AURAOSMBusLinesProcessor.fetch(reload_pipeline=False)
osm_lines_gdf.head()

,gtfs_id,osm_id,name,from_location,to,network,network_gtfs_id,network_wikidata,operator,colour,text_colour,stop_gtfs_ids,stops_osm_ids,school,geometry,other
0,NaN,197669,40 : Bellecour ⇒ Neuville,Bellecour,Neuville,TCL,None,Q8700,Keolis Lyon,#965340,NaN,[],"[4619742845, 2321205056, 2321205046, 210715756...",False,None,"{'bicycle': None, 'boundary': None, 'by_night'..."
1,NaN,207979,C7 : Gare Part-Dieu - Vivier Merle ⇒ Hôpital L...,Gare Part-Dieu - Vivier Merle,Hôpital Lyon Sud,TCL,None,Q8700,Keolis Lyon,NaN,NaN,[],"[7376670890, 11596032483, 4576330319, 65875533...",False,None,"{'bicycle': None, 'boundary': None, 'by_night'..."
2,NaN,225734,Bus 80 : Bel-Air → Saint-Julien SNCF,Bel-Air,Saint-Julien SNCF,Unireso,None,Q1312883,TPG: GEM Bus,#f5b5d2,NaN,[],"[8253534546, 8253534547, 6053855877, 654431699...",False,None,"{'bicycle': None, 'boundary': None, 'by_night'..."
3,NaN,225735,Bus 80 : Saint-Julien SNCF → Bel-Air,Saint-Julien SNCF,Bel-Air,Unireso,None,Q1312883,TPG: GEM Bus,#f5b5d2,NaN,[],"[10085904782, 7872312632, 1033278418, 45944552...",False,None,"{'bicycle': None, 'boundary': None, 'by_night'..."
4,NaN,310305,17 : Gare d'Oullins ⇒ Vourles Z.A. Les Plattes,Gare d'Oullins,Vourles Z.A. Les Plattes,TCL,None,Q8700,Keolis Lyon,#F7941D,NaN,[],"[7495230391, 4645286989, 4645287006, 325711244...",False,None,"{'bicycle': None, 'boundary': None, 'by_night'..."

In [7]:
# activity_gdf = gpd.read_parquet("src/data/C2C/depart_topos_stops_isere.parquet")
# print(f"{len(activity_gdf)} activity points")
# activity_gdf.rename(
#     columns={"navitia_id": "Id wp", "name": "Name wp", "nombre_de_depart_de_topo": "nbr_topo"},
#     inplace=True,
# )
# activity_gdf = activity_gdf[["Id wp", "Name wp", "geometry", "nbr_topo"]]
# activity_gdf.head()
access_point_df = pd.read_csv(
    DATA_FOLDER / "C2C/c2corg-anonymized.2025-12-10.access_points.csv"
)
print(f"{len(access_point_df)} access points")
activity_gdf = gpd.GeoDataFrame(
    access_point_df,
    geometry=[
        Point(xy) for xy in zip(access_point_df["lon"], access_point_df["lat"], strict=True)
    ],
    crs=EPSG_WGS84,
)
activity_gdf = activity_gdf.rename(
    columns={
        "document_id": "Id wp",
        "title": "Name wp",
    }
)
activity_gdf["nbr_topo"] = "?"
activity_gdf.head()

8157 access points

,Id wp,lon,lat,Name wp,description,summary,geometry,nbr_topo
0,1147027,55.364058,-21.021794,Parking des Cryptomérias,"Accès depuis Saint-Paul en 45min, route en exc...",Parking de départ pour plusieurs circuits à pi...,POINT (55.36406 -21.02179),?
1,1186548,-0.358590,42.779283,Formigal - Village,NaN,Se garer à proximité de l'hôtel HG Alto Aragon...,POINT (-0.35859 42.77928),?
2,1587979,170.816308,-43.858069,Fox Peak ski field,NaN,NaN,POINT (170.81631 -43.85807),?
3,952546,14.510288,46.057894,Ljubljana,NaN,Ljubljana est la capitale de la Slovénie. Nomb...,POINT (14.51029 46.05789),?
4,44261,7.149976,44.202556,Col de la Lombarde,[img=439892 right]col de la Lombarde[/img]\r\n,NaN,POINT (7.14998 44.20256),?

In [8]:
area_gdf = gpd.read_file(DATA_FOLDER / "transportdatagouv/contour-des-departements.geojson")
area_gdf = area_gdf.set_crs(EPSG_WGS84, allow_override=True)
area_gdf.head()

,code,nom,geometry
0,01,Ain,"POLYGON ((4.78021 46.17668, 4.78024 46.18905, ..."
1,02,Aisne,"POLYGON ((3.17296 50.01131, 3.17382 50.01186, ..."
2,03,Allier,"POLYGON ((3.03207 46.79491, 3.03424 46.7908, 3..."
3,04,Alpes-de-Haute-Provence,"POLYGON ((5.67604 44.19143, 5.67817 44.19051, ..."
4,05,Hautes-Alpes,"POLYGON ((6.26057 45.12685, 6.26417 45.12641, ..."

In [9]:
department_activity_df = (
    gpd.sjoin(
        activity_gdf.to_crs(EPSG_WGS84),
        area_gdf[area_gdf["code"] == department_code],
    )
    .loc[:, ["Id wp"]]
    .drop_duplicates()
    .merge(activity_gdf, on="Id wp", how="inner")
)
department_activity_gdf = gpd.GeoDataFrame(department_activity_df, geometry="geometry").set_crs(
    EPSG_WGS84
)
print(
    f"Filter on department {department_code}: keep {len(department_activity_gdf)} on {len(activity_gdf)} activity points"
)

Filter on department 74: keep 531 on 8157 activity points

In [10]:
tdg_stop_list = []
for area_code in [department_code] + neighbour_department_codes[department_code]:
    tdg_file = DATA_FOLDER / f"transportdatagouv/stops_{area_code}.parquet"
    if not tdg_file.exists():
        err_msg = f"No TransportDataGouv bus stops found for area code {area_code}, please process it first."
        print(err_msg)
    else:
        tdg_stop_list.append(gpd.read_parquet(tdg_file))
tdg_stops_gdf = pd.concat(tdg_stop_list, ignore_index=True)
tdg_stops_gdf.columns = [
    "network_gtfs_id",
    "network",
    "gtfs_id",
    "name",
    "stop_code",
    "description",
    "line_gtfs_ids",
    "geometry",
]
tdg_stops_gdf.loc[:, "source"] = "TDG"
tdg_stops_gdf.head()

No TransportDataGouv bus stops found for area code 1, please process it first.

,network_gtfs_id,network,gtfs_id,name,stop_code,description,line_gtfs_ids,geometry,source
0,1,Réseau STAR'T,AL_BOUG1,Allinges Bougeries haut,<NA>,,"{'line_id': 'N', 'line_name': 'N'}",POINT (721701.703 5836692.071),TDG
1,1,Réseau STAR'T,AL_BOUG2,Allinges Bougeries haut,<NA>,,"{'line_id': 'N', 'line_name': 'N'}",POINT (721686.151 5836788.756),TDG
2,1,Réseau STAR'T,AL_CENT1,Centenaire,<NA>,,"{'line_id': 'N', 'line_name': 'N'}",POINT (721763.463 5835401.431),TDG
3,1,Réseau STAR'T,AL_CENT2,Centenaire,<NA>,,"{'line_id': 'N', 'line_name': 'N'}",POINT (721735.688 5835376.292),TDG
4,1,Réseau STAR'T,AL_CHVI2,Châteauvieux,<NA>,,"{'line_id': 'N', 'line_name': 'N'}",POINT (720216.634 5833207.795),TDG

In [11]:
from src.processors.c2c import C2CBusStopsProcessor

In [12]:
c2c_stops_gdf = C2CBusStopsProcessor.fetch(reload_pipeline=False).to_crs(EPSG_WGS84)
c2c_stops_gdf.loc[:, "source"] = "C2C"
c2c_stops_gdf.head()

,gtfs_id,navitia_id,osm_id,name,description,line_gtfs_ids,line_osm_ids,network,network_gtfs_id,geometry,other,source
0,None,stop_area:OVO:S1000374,None,La Sure en Chartreuse - RD520 Village (La Sure...,None,[],[],M Réso - Pays Voironnais,None,POINT (5.65312 45.31916),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C
1,None,stop_area:O38:4038505,None,RD520 Pommiers Village (La Sure en Chartreuse),None,[],[],Isère - Transisère,None,POINT (5.65302 45.31893),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C
2,None,stop_area:OVO:S1002339,None,La Sure en Chartreuse - Pommiers Village (La S...,None,[],[],M Réso - Pays Voironnais,None,POINT (5.65543 45.31862),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C
3,None,stop_area:OVO:S1001416,None,La Sure en Chartreuse - les Barniers (La Sure ...,None,[],[],M Réso - Pays Voironnais,None,POINT (5.65098 45.3155),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C
4,None,stop_area:O38:3279412,None,Les Barniers (La Sure en Chartreuse),None,[],[],Isère - Transisère,None,POINT (5.65103 45.31545),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C

In [13]:
# old_bus_stop_nb = len(c2c_stops_gdf)
# valid_navitia_ids = gpd.sjoin(c2c_stops_gdf, area_gdf[area_gdf["code"] == isere_code])[
#     "navitia_id"
# ].drop_duplicates()
# c2c_stops_gdf = c2c_stops_gdf[c2c_stops_gdf["navitia_id"].isin(valid_navitia_ids)]
# print(f"Filter on Isère: keep {len(c2c_stops_gdf)} on {old_bus_stop_nb} C2C bus stops")

In [14]:
all_stops_gdf = pd.concat(
    (osm_stops_gdf, tdg_stops_gdf.to_crs(EPSG_WGS84), c2c_stops_gdf.to_crs(EPSG_WGS84))
)
all_stops_gdf.tail()

,gtfs_id,navitia_id,osm_id,name,description,line_gtfs_ids,line_osm_ids,network,network_gtfs_id,geometry,other,source,stop_code
1259,None,stop_area:ZOS:Navitia:10407-0500300,None,LHôpital Parking (Aiguilles),None,[],[],ZOU ! Scolaire,None,POINT (6.86861 44.78044),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C,NaN
1260,None,stop_area:ZOS:Navitia:11868-0500300,None,École Félix Tonda (Aiguilles),None,[],[],ZOU ! Scolaire,None,POINT (6.86689 44.78005),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C,NaN
1261,None,stop_area:O66:66S03936,None,Arles-sur-Tech - Chbre des Métiers (Arles-sur-...,None,[],[],Pyrénées-Orientales - liO Occitanie,None,POINT (2.63124 42.45584),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C,NaN
1262,None,stop_area:O66:66S03937,None,Arles-sur-Tech - Gare Routière (Arles-sur-Tech),None,[],[],Pyrénées-Orientales - liO Occitanie,None,POINT (2.63619 42.4584),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C,NaN
1263,None,stop_area:R74:Navitia:FR:74134:ZE:58693:HAUTEx...,None,Les Clos (Les Gets),None,[],[],Haute-Savoie - Réseau interurbain 74,None,POINT (6.66143 46.15386),"{'srid': 3857, 'stoparea_id_and_line': [{'line...",C2C,NaN

In [15]:
from src.processors.distances import DistancesProcessor

In [16]:
distance_threshold_km = 5

In [17]:
distances_df = DistancesProcessor.fetch(reload_pipeline=False)
distances_df.loc[distances_df["distance_m"] > distance_threshold_km * 1000, "distance_m"] = None
nb_lines_before_drop = len(distances_df)
distances_df = distances_df[~pd.isnull(distances_df["distance_m"])]
distances_df = distances_df[
    distances_df["Id wp"].isin(department_activity_df["Id wp"].unique())
]
print(f"{len(distances_df)} distances kept on {nb_lines_before_drop}")
distances_df.head()

50217 distances kept on 79237337

           osm_id gtfs_id navitia_id    Id wp  distance_m  computed
7021   13798988.0     NaN        NaN   978831      2598.9      True
7028   13798988.0     NaN        NaN  1203699      3433.3      True
7041   13798988.0     NaN        NaN  1205899      4282.3      True
12040  23719915.0     NaN        NaN   337068      4346.6      True
12081  23719915.0     NaN        NaN  1204814      3926.5      True

## Analyse data

In [18]:
activity_gdf["Category"] = "Unreachable"
activity_gdf.loc[~activity_gdf["Id wp"].isin(department_activity_df["Id wp"]), "Category"] = (
    "Outside departement"
)
activity_gdf.loc[activity_gdf["Id wp"].isin(distances_df["Id wp"].unique()), "Category"] = (
    "Reachable"
)
activity_gdf.groupby("Category").count()["Id wp"]

Category
Outside departement    7626
Reachable               500
Unreachable              31
Name: Id wp, dtype: int64

### C2C

In [19]:
near_c2c_stops_gdf = c2c_stops_gdf[
    c2c_stops_gdf["navitia_id"].isin(distances_df["navitia_id"].unique())
]
print(
    f"{len(near_c2c_stops_gdf)} C2C bus stops are near activity points (on {len(c2c_stops_gdf)} bus stops)"
)

222 C2C bus stops are near activity points (on 1264 bus stops)

In [20]:
department_navitia_ids = gpd.sjoin(
    c2c_stops_gdf, area_gdf[area_gdf["code"] == department_code]
)["navitia_id"].drop_duplicates()
print(f"{len(department_navitia_ids)} bus stops in the department")

219 bus stops in the department

In [21]:
c2c_interesting_columns = ["navitia_id", "name", "network", "geometry", "source", "lines"]
expanded = c2c_stops_gdf["other"].apply(pd.Series)
expanded_c2c_stops_gdf = pd.concat([c2c_stops_gdf.drop(columns=["other"]), expanded], axis=1)
expanded_c2c_stops_gdf["lines"] = expanded_c2c_stops_gdf["stoparea_id_and_line"].apply(
    lambda l: [e["line"] for e in l]
)
expanded_c2c_stops_gdf[c2c_interesting_columns].head()

,navitia_id,name,network,geometry,source,lines
0,stop_area:OVO:S1000374,La Sure en Chartreuse - RD520 Village (La Sure...,M Réso - Pays Voironnais,POINT (5.65312 45.31916),C2C,[Bus 503 - POMMIER PALLACHERE - VOREPPE GARE S...
1,stop_area:O38:4038505,RD520 Pommiers Village (La Sure en Chartreuse),Isère - Transisère,POINT (5.65302 45.31893),C2C,"[Bus T40 - ST PIERRE DE CHARTREUSE-GRENOBLE, B..."
2,stop_area:OVO:S1002339,La Sure en Chartreuse - Pommiers Village (La S...,M Réso - Pays Voironnais,POINT (5.65543 45.31862),C2C,[Bus 503 - POMMIER PALLACHERE - VOREPPE GARE S...
3,stop_area:OVO:S1001416,La Sure en Chartreuse - les Barniers (La Sure ...,M Réso - Pays Voironnais,POINT (5.65098 45.3155),C2C,[Bus 503 - POMMIER PALLACHERE - VOREPPE GARE S...
4,stop_area:O38:3279412,Les Barniers (La Sure en Chartreuse),Isère - Transisère,POINT (5.65103 45.31545),C2C,"[Bus T40 - ST PIERRE DE CHARTREUSE-GRENOBLE, B..."

In [22]:
c2c_distances = distances_df.merge(
    expanded_c2c_stops_gdf[c2c_interesting_columns].explode("lines"),
    on="navitia_id",
    how="inner",
)
c2c_distances.head()

,osm_id,gtfs_id,navitia_id,Id wp,distance_m,computed,name,network,geometry,source,lines
0,NaN,NaN,stop_area:R74:Navitia:FR:74083:ZE:58837:HAUTEx...,170094,2385.8,True,Lycée H.B. de Saussure (Combloux),Haute-Savoie - Réseau interurbain 74,POINT (6.64006 45.89711),C2C,Bus Y81 - CHAMONIX > CLUSES
1,NaN,NaN,stop_area:R74:Navitia:FR:74083:ZE:58837:HAUTEx...,170094,2385.8,True,Lycée H.B. de Saussure (Combloux),Haute-Savoie - Réseau interurbain 74,POINT (6.64006 45.89711),C2C,Bus Y83 - SALLANCHES > PRAZ > FLUMET
2,NaN,NaN,stop_area:R74:Navitia:FR:74083:ZE:58837:HAUTEx...,170094,2385.8,True,Lycée H.B. de Saussure (Combloux),Haute-Savoie - Réseau interurbain 74,POINT (6.64006 45.89711),C2C,Bus Y81 - CHAMONIX > CLUSES
3,NaN,NaN,stop_area:R74:Navitia:FR:74083:ZE:58837:HAUTEx...,170094,2385.8,True,Lycée H.B. de Saussure (Combloux),Haute-Savoie - Réseau interurbain 74,POINT (6.64006 45.89711),C2C,Bus Y83 - SALLANCHES > PRAZ > FLUMET
4,NaN,NaN,stop_area:R74:Navitia:FR:74083:ZE:58837:HAUTEx...,465228,4551.3,True,Lycée H.B. de Saussure (Combloux),Haute-Savoie - Réseau interurbain 74,POINT (6.64006 45.89711),C2C,Bus Y81 - CHAMONIX > CLUSES

In [23]:
reachable_c2c_nb = len(c2c_distances[~pd.isnull(c2c_distances["navitia_id"])]["Id wp"].unique())
print(f"{reachable_c2c_nb} activity point access are reachable with C2C data")

254 activity point access are reachable with C2C data

In [24]:
c2c_mask = c2c_distances["distance_m"] == c2c_distances.groupby(["Id wp", "lines"])[
    "distance_m"
].transform("min")
c2c_neareast_stops_by_line_gdf = expanded_c2c_stops_gdf[
    expanded_c2c_stops_gdf["navitia_id"].isin(c2c_distances[c2c_mask]["navitia_id"].unique())
]
print(
    f"{len(c2c_neareast_stops_by_line_gdf)} C2C bus stops are the nearest activity points for their bus line (on {len(c2c_stops_gdf)} bus stops)"
)

162 C2C bus stops are the nearest activity points for their bus line (on 1264 bus stops)

In [25]:
assert (
    reachable_c2c_nb
    == c2c_distances[
        c2c_distances["navitia_id"].isin(c2c_neareast_stops_by_line_gdf["navitia_id"])
    ]["Id wp"].nunique()
), "Some activity points are no more reachable with only c2c_neareast_stops_by_line_gdf"

### OSM

In [26]:
osm_interesting_columns = [
    "osm_id",
    "name",
    "description",
    "line_osm_ids",
    "network",
    "geometry",
    "source",
]
osm_distances = distances_df.merge(
    osm_stops_gdf[osm_interesting_columns].explode("line_osm_ids"), on="osm_id", how="inner"
)
osm_distances.head()

,osm_id,gtfs_id,navitia_id,Id wp,distance_m,computed,name,description,line_osm_ids,network,geometry,source
0,13798988.0,NaN,NaN,978831,2598.9,True,La Comtesse,NaN,3620143,NaN,POINT (6.71308 45.8911),OSM
1,13798988.0,NaN,NaN,978831,2598.9,True,La Comtesse,NaN,3620146,NaN,POINT (6.71308 45.8911),OSM
2,13798988.0,NaN,NaN,978831,2598.9,True,La Comtesse,NaN,3620147,NaN,POINT (6.71308 45.8911),OSM
3,13798988.0,NaN,NaN,1203699,3433.3,True,La Comtesse,NaN,3620143,NaN,POINT (6.71308 45.8911),OSM
4,13798988.0,NaN,NaN,1203699,3433.3,True,La Comtesse,NaN,3620146,NaN,POINT (6.71308 45.8911),OSM

In [27]:
# Keep one bus stop by line and activity
osm_mask = osm_distances["distance_m"] == osm_distances.groupby(["Id wp", "line_osm_ids"])[
    "distance_m"
].transform("min")
osm_neareast_stops_by_line_gdf = osm_stops_gdf[
    osm_stops_gdf["osm_id"].isin(osm_distances[osm_mask]["osm_id"].unique())
]

# For each activity keep also one bus stop with no line data
osm_stops_ids_without_lines = osm_stops_gdf[
    osm_stops_gdf["line_osm_ids"].apply(lambda l: len(l) == 0)
]["osm_id"].unique()
osm_distances_without_lines = osm_distances[
    osm_distances["osm_id"].isin(osm_stops_ids_without_lines)
]
osm_without_lines_mask = osm_distances_without_lines[
    "distance_m"
] == osm_distances_without_lines.groupby(["Id wp"])["distance_m"].transform("min")
osm_neareast_stops_without_line_gdf = osm_stops_gdf[
    osm_stops_gdf["osm_id"].isin(
        osm_distances_without_lines[osm_without_lines_mask]["osm_id"].unique()
    )
]

# Concat them
osm_neareast_stops_by_line_gdf = pd.concat(
    (osm_neareast_stops_by_line_gdf, osm_neareast_stops_without_line_gdf)
)
print(
    f"{len(osm_neareast_stops_by_line_gdf)} OSM bus stops are the nearest activity points for their bus line (on {len(osm_stops_gdf)} bus stops)"
)

695 OSM bus stops are the nearest activity points for their bus line (on 35498 bus stops)

In [28]:
line_osm_id_to_name = osm_lines_gdf.set_index("osm_id")["name"].to_dict()
osm_neareast_stops_by_line_gdf.loc[:, "lines"] = osm_neareast_stops_by_line_gdf.loc[
    :, "line_osm_ids"
].apply(lambda l: [line_osm_id_to_name[e] for e in l])

In [29]:
reachable_osm_nb = len(osm_distances[~pd.isnull(osm_distances["osm_id"])]["Id wp"].unique())
print(f"{reachable_osm_nb} activity point access are reachable with OSM data")

488 activity point access are reachable with OSM data

In [30]:
assert (
    reachable_osm_nb
    == osm_distances[osm_distances["osm_id"].isin(osm_neareast_stops_by_line_gdf["osm_id"])][
        "Id wp"
    ].nunique()
), "Some activity points are no more reachable with only osm_neareast_stops_by_line_gdf"

### TDG

In [31]:
tdg_interesting_columns = ["gtfs_id", "name", "line_gtfs_ids", "network", "geometry", "source"]
tdg_distances = distances_df.merge(
    tdg_stops_gdf[tdg_interesting_columns], on="gtfs_id", how="inner"
)
tdg_distances.head()

,osm_id,gtfs_id,navitia_id,Id wp,distance_m,computed,name,line_gtfs_ids,network,geometry,source
0,NaN,motchat1,NaN,131619,3585.0,True,Motz Chateaufort,"{'line_id': '501', 'line_name': '501'},{'line_...",Ondéa Grand Lac,POINT (649271.375 5768778.337),TDG
1,NaN,motchat2,NaN,131619,3585.0,True,Motz Chateaufort,"{'line_id': '505', 'line_name': '505'},{'line_...",Ondéa Grand Lac,POINT (649271.375 5768778.337),TDG
2,NaN,motchef1,NaN,131619,4978.2,True,Motz Chef-lieu Mairie,"{'line_id': '502', 'line_name': '502'},{'line_...",Ondéa Grand Lac,POINT (650930.258 5767470.891),TDG
3,NaN,motchef2,NaN,131619,4981.9,True,Motz Chef-lieu Mairie,"{'line_id': '502', 'line_name': '502'}",Ondéa Grand Lac,POINT (650942.949 5767477.932),TDG
4,NaN,ptreg3,NaN,131619,4978.2,True,Motz Chef-lieu Mairie,"{'line_id': '506', 'line_name': '506'}",Ondéa Grand Lac,POINT (650930.258 5767470.891),TDG

In [32]:
tdg_mask = tdg_distances["distance_m"] == tdg_distances.groupby(["Id wp", "line_gtfs_ids"])[
    "distance_m"
].transform("min")
tdg_neareast_stops_by_line_gdf = tdg_stops_gdf[
    tdg_stops_gdf["gtfs_id"].isin(tdg_distances[tdg_mask]["gtfs_id"].unique())
]
print(
    f"{len(tdg_neareast_stops_by_line_gdf)} tdg bus stops are the nearest activity points for their bus line (on {len(tdg_stops_gdf)} bus stops)"
)

2262 tdg bus stops are the nearest activity points for their bus line (on 14350 bus stops)

In [33]:
reachable_tdg_nb = len(tdg_distances[~pd.isnull(tdg_distances["gtfs_id"])]["Id wp"].unique())
print(f"{reachable_tdg_nb} activity point access are reachable with TDG data")

466 activity point access are reachable with TDG data

In [34]:
assert (
    reachable_tdg_nb
    == tdg_distances[tdg_distances["gtfs_id"].isin(tdg_neareast_stops_by_line_gdf["gtfs_id"])][
        "Id wp"
    ].nunique()
), "Some activity points are no more reachable with tdg_neareast_stops_by_line_gdf"

# Visualize

## All activity points

In [36]:
color_mapping = {"Outside departement": "gray", "Reachable": "green", "Unreachable": "purple"}
activity_gdf["color"] = activity_gdf["Category"].apply(lambda c: color_mapping[c])

In [37]:
reachable_nb = sum(activity_gdf["Category"] == "Reachable")
unreachable_nb = sum(activity_gdf["Category"] == "Unreachable")
outside_nb = sum(activity_gdf["Category"] == "Outside departement")
title_html = f"""
    <h4 style="position: fixed; top: 10px; left: 50px; z-index: 9999; background: rgba(255,255,255,0.8); padding: 6px 10px; margin: 0;">
    Points d'accès d'activité CampToCamp.<br>
    - {reachable_nb} points à moins de {distance_threshold_km}km d'un arrêt de bus (<span style=\"color: green\">vert</span>)<br>
    - {unreachable_nb} points à plus de {distance_threshold_km}km d'un arrêt de bus (<span style=\"color: purple\">violet</span>)<br>
    - {outside_nb} points en dehors du département (<span style=\"color: gray\">gris</span>)
    </h4>
"""

In [38]:
# Plot points with bus data far from distance_threshold m

# Add a base OSM map centered on Grenoble
m = folium.Map(
    location=[45.1885, 5.7245], zoom_start=9, tiles="OpenStreetMap", control_scale=True
)

# Add Waymarked Trails hiking layers
folium.TileLayer(tiles="WaymarkedTrails.hiking").add_to(m)

# Add Isère polygon
isere_latlon_coords = [
    (lat, lon)
    for lon, lat in area_gdf[area_gdf["code"] == department_code]["geometry"]
    .values[0]
    .exterior.coords
]
folium.Polygon(
    locations=isere_latlon_coords,
    color="black",
    weight=3,
    fill_color="black",
    fill_opacity=0.25,
    fill=True,
).add_to(m)

# Add activity markers
columns_to_display = ["Id wp", "Name wp", "nbr_topo"]
folium.GeoJson(
    activity_gdf[columns_to_display + ["color", "geometry"]],
    zoom_on_click=True,
    marker=folium.Marker(icon=folium.Icon(icon="star")),
    tooltip=folium.GeoJsonTooltip(fields=columns_to_display),
    popup=folium.GeoJsonPopup(fields=columns_to_display),
    style_function=lambda x: {
        "markerColor": x["properties"]["color"],
    },
).add_to(m)

# Add title
m.get_root().html.add_child(folium.Element(title_html))

m

In [39]:
m.save("all_activity_points.html")

## Filtered bus data with activities

In [40]:
import json

In [41]:
def list_to_str_with_br(l: list[str], line_number_limit: int = 10) -> str:
    list_to_process = l[:line_number_limit]
    if len(l) > line_number_limit:
        list_to_process += ["..."]
    return "<br>".join(list_to_process)

In [42]:
def get_tdg_line_names(lines: str) -> str:
    lines_json = "[" + lines.replace("'", '"') + "]"
    # TODO Remove this bugfix
    lines_json = lines_json.replace('Mobi"Aix', "Mobi'Aix")
    data = json.loads(lines_json)
    return list_to_str_with_br([d["line_name"] for d in data])

In [43]:
bus_stop_nb = {
    "TDG": len(tdg_neareast_stops_by_line_gdf),
    "OSM": len(osm_neareast_stops_by_line_gdf),
    "C2C": len(c2c_neareast_stops_by_line_gdf),
}
fields_by_source = {
    "TDG": ["gtfs_id", "name", "network", "line_gtfs_ids"],
    "OSM": ["osm_id", "name", "network", "lines"],
    "C2C": ["navitia_id", "name", "network", "lines"],
}
aliases_by_source = {
    "TDG": [f"<b>Arrêt de bus TDG</b><br>ID :", "Nom :", "Réseau :", "Lignes :"],
    "OSM": [f"<b>Arrêt de bus OSM</b><br>ID :", "Nom :", "Réseau :", "Lignes :"],
    "C2C": [f"<b>Arrêt de bus C2C</b><br>ID :", "Nom :", "Réseau :", "Lignes :"],
}
tdg_stops_to_plot = tdg_neareast_stops_by_line_gdf[
    fields_by_source["TDG"] + ["geometry"]
].copy()
tdg_stops_to_plot["line_gtfs_ids"] = tdg_neareast_stops_by_line_gdf["line_gtfs_ids"].apply(
    get_tdg_line_names
)
osm_stops_to_plot = osm_neareast_stops_by_line_gdf[
    fields_by_source["OSM"] + ["geometry"]
].copy()
osm_stops_to_plot["lines"] = osm_stops_to_plot["lines"].apply(list_to_str_with_br)
c2c_stops_to_plot = c2c_neareast_stops_by_line_gdf[
    fields_by_source["C2C"] + ["geometry"]
].copy()
c2c_stops_to_plot["lines"] = c2c_stops_to_plot["lines"].apply(list_to_str_with_br)
gdf_by_source = {"TDG": tdg_stops_to_plot, "OSM": osm_stops_to_plot, "C2C": c2c_stops_to_plot}

In [44]:
title_html = f"""
    <div style="position: fixed; top: 10px; left: 50px; z-index: 9999; background: rgba(255,255,255,0.8); padding: 6px 10px; margin: 0;">
        <h2>Couverture des points d'accès CampToCamp<br>desservis ou non par arrêts de bus<br>(selon sources associés : TDG, OSM, C2C)</h2>
        <h4>
            - {reachable_nb} points à moins de {distance_threshold_km}km d'un arrêt de bus (<span style=\"color: green\">vert</span>)<br>
            - {unreachable_nb} points à plus de {distance_threshold_km}km d'un arrêt de bus (<span style=\"color: purple\">violet</span>)<br>
            <br>
            - {reachable_tdg_nb} points accessibles avec les données TDG<br>
            - {reachable_osm_nb} points accessibles avec les données OSM<br>
            - {reachable_c2c_nb} points accessibles avec les données C2C<br>
        </h4>
    </div>
"""

In [45]:
# Add a base OSM map centered on Grenoble
m = folium.Map(
    location=[45.1885, 5.7245], zoom_start=9, tiles="OpenStreetMap", control_scale=True
)

# Add Waymarked Trails hiking layers
folium.TileLayer(tiles="WaymarkedTrails.hiking", control=False).add_to(m)

# Add Isère polygon
isere_latlon_coords = [
    (lat, lon)
    for lon, lat in area_gdf[area_gdf["code"] == department_code]["geometry"]
    .values[0]
    .exterior.coords
]
folium.Polygon(
    locations=isere_latlon_coords,
    color="black",
    weight=3,
    fill_color="black",
    fill_opacity=0.25,
    fill=True,
).add_to(m)

# Add bus markers
source_to_id = {"TDG": "gtfs_id", "OSM": "osm_id", "C2C": "navitia_id"}
for source in ["TDG", "OSM", "C2C"]:
    fg = folium.FeatureGroup(name=f"Bus stops from {source} ({bus_stop_nb[source]})", show=True)
    fields = fields_by_source[source]
    aliases = aliases_by_source[source]
    folium.GeoJson(
        gdf_by_source[source][fields + ["geometry"]],
        zoom_on_click=True,
        marker=folium.Marker(icon=folium.Icon(icon="bus", prefix="fa", color="blue")),
        tooltip=folium.GeoJsonTooltip(fields=fields, aliases=aliases),
        popup=folium.GeoJsonPopup(fields=fields, aliases=aliases),
    ).add_to(fg)
    fg.add_to(m)


# Add activity markers
fg = folium.FeatureGroup(name="C2C activity access point", show=True)
aliases = [f"<b>Point d'accès d'activité</b><br>ID :", "Nom :", "Nombre de topos :"]
folium.GeoJson(
    activity_gdf[activity_gdf["Category"] != "Outside departement"][
        columns_to_display + ["color", "geometry"]
    ],
    zoom_on_click=True,
    marker=folium.Marker(icon=folium.Icon(icon="star")),
    tooltip=folium.GeoJsonTooltip(fields=columns_to_display, aliases=aliases),
    popup=folium.GeoJsonPopup(fields=columns_to_display, aliases=aliases),
    style_function=lambda x: {
        "markerColor": x["properties"]["color"],
    },
).add_to(fg)
fg.add_to(m)

# Add layer control to filter layers
folium.LayerControl(collapsed=False).add_to(m)

# Add title
m.get_root().html.add_child(folium.Element(title_html))

m

In [46]:
m.save(
    f"one_bus_by_line_and_source_at_distance_{distance_threshold_km}_km_department_{department_code}.html"
)